In [1]:
#!pip install openpyxl
import numpy as np
import pandas as pd

In [2]:
w27_31verticesFile = "C:\RaghusWork\Jan-08-24\Week27Toward31 - vertices.xlsx"
w31_27verticesFile = "C:\RaghusWork\Jan-08-24\Week31For27 - vertices.xlsx"
w27_31trianglesFile = "C:\RaghusWork\Jan-08-24\Week27Toward31_triangles.csv"

In [3]:
w27_31vertices = pd.read_excel(w27_31verticesFile, header=None, engine='openpyxl') #.replace('/','\\') 
w31_27vertices = pd.read_excel(w31_27verticesFile, header=None, engine='openpyxl')
w27_31triangles = pd.read_csv(w27_31trianglesFile, sep=',', header=None)

In [7]:
print(len(w27_31vertices.index),len(w31_27vertices.index),len(w27_31triangles.index))
print(w27_31vertices.shape, w31_27vertices.shape, w27_31triangles.shape)
#w27_31vertices.head(), w31_27vertices.head(), w27_31triangles.head()

10242 10242 2448
(10242, 3) (10242, 3) (2448, 3)


In [10]:
#compute growth vectors
growthVector = w31_27vertices - w27_31vertices
#len(w27_31vertices.index)
#w27_31vertices.head(), w31_27vertices.head(), growthVector.head()

In [17]:
outDf = pd.DataFrame(columns=('a1', 'a2', 'a3', 'b1', 'b2', 'b3', 'c1', 'c2', 'c3'))
for index, edges in w27_31triangles.iterrows():
    if (index>2):
        break
    vertex0 = w27_31vertices.iloc[edges[0]].to_numpy()
    vertex1 = w27_31vertices.iloc[edges[1]].to_numpy()
    vertex2 = w27_31vertices.iloc[edges[2]].to_numpy()
    normal = np.cross(vertex1-vertex0, vertex2-vertex0)
    G0 = growthVector.iloc[edges[0]].to_numpy()
    G1 = growthVector.iloc[edges[1]].to_numpy()
    G2 = growthVector.iloc[edges[2]].to_numpy()
    n2 = np.dot(normal,normal)
    a = 
    print(edges[0],edges[1],edges[2])  
    print(vertex0,vertex1,vertex2,normal,n2)

7625 7574 7589
[-1.20489407 -7.00229549 26.56610298] [-1.15847349  0.35071763 26.2598362 ] [-1.3211534   1.08094466 26.83415222] [4.44659755 0.02316337 1.23008508] 21.28587563001819
5405 361 5390
[-28.03792763  -8.73671818  -1.49171972] [-27.97730255  -8.89196396   0.67034614] [-27.82284737  -7.84055805  -0.19920878] [-2.13821409  0.38665912  0.08772008] 4.729159564997622
1899 7392 7372
[-1.16453958 16.94563675 17.23245621] [-0.92615926 16.51556969 16.21819687] [-1.28907728 11.53064728 22.11014557] [-7.58993717 -1.03643158 -1.34438645] 60.48871165559712
